resources:
- name: git
  type: git
  source:
    uri: git@github.com:grapeup/filesystem-bbr-boshrelease.git
    branch: master
    private_key: ((github_private_key))

- name: version
  type: semver
  source :
    driver: s3
    bucket: ((version_bucket))
    region_name: ((version_bucket_region))
    key: version
    access_key_id: ((aws_access_key))
    secret_access_key: ((aws_secret_access_key))
    initial_version: "1.3.1"


- name: github
  type: github-release
  source:
    user:         grapeup
    repository:   filesystem-bbr-boshrelease
    access_token: ((github_token))

jobs:
- name: minor
  public: true
  plan:
  - do:
    - { get: version, trigger: false, params: {bump: minor} }
    - { put: version,                 params: {file: version/number} }

- name: major
  public: true
  plan:
  - do:
    - { get: version, trigger: false, params: {bump: major} }
    - { put: version,                 params: {file: version/number} }

- name: shipit
  public: true
  serial: true
  plan:
  - name: inputs
    aggregate:
      - { get: version, params: {bump: final} }
      - { get: git }

  - name: release
    task: release
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: concourse/bosh-cli
          tag: latest
      inputs:
        - name: version
        - name: git
      outputs:
        - name: pushme
        - name: notifications
        - name: gh
      run:
        path: ./git/ci/scripts/shipit.sh
        args: []
      params:
        REPO_ROOT:      git
        VERSION_FROM:   version/number
        REPO_OUT:       pushme
        BRANCH:         master
        GITHUB_OWNER:   grapeup
        GIT_EMAIL:      ci@cloudboostr.com
        GIT_NAME:       Cloudboostr CI Bot
        AWS_ACCESS_KEY: ((aws_access_key))
        AWS_SECRET_KEY: ((aws_secret_access_key))

  - name: upload-git
    put: git
    params:
      rebase: true
      repository: pushme/git

  - name: github
    put: github
    params:
      name:   gh/name
      tag:    gh/tag
  
  - name: version-bump
    put: version
    params:
      bump: patch
